apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["default/hw3demo1"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2024-04-19T20:36:08Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"2a6960c9-de6b-4753-880c-81349e87e15d"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-04-19T20:36:08Z'
  name: hw3demo1
  namespace: default
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: hw3demo1
      uid: 2a6960c9-de6b-4753-880c-81349e87e15d
  resourceVersion: '7222'
  uid: c70f896b-b95c-458c-a1de-70ae42cb7be3
spec:
  clusterIP: 10.43.240.14
  clusterIPs:
    - 10.43.240.14
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: 8080tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-hw3demo1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
